spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CapstoneDB
    username: root
    password: root@123
server:
  port: 8087
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
